import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        EXP_BLUE: "#1363DF",
        EXP_RED: "#DD170F",
        EXP_GRAY: "#BBBBBB",
        EXP_FIELD_NAME: "#666666",
        EXP_FIELD_DISABLED: "#999999",
        EXP_BG: "#FAF8F8",
        EXP_HEADING: "#333333",
        EXP_OUTLINE: "#CCCCCC",
        EXP_DOT: "#D9D9D9",
        EXP_BACKGROUND: "rgba(19, 99, 223, 0.1)",
        EXP_GREEN: "#5BC93F",
        EXP_WHITE: "#FFFFFF",
        EXP_HOVER: "#F9FAFB",
        EXP_HBL_BORDER: "#DDDDDD",
        EXP_BG_BLUE: "#F5F5F5",
        EXP_BORDER_LIGHT: "#F2F4F7",
        EXP_LANDING_BG: "#E7EFFC",
        EXP_VIDEO_BG: "#0A2647",
        EXP_FEATURES_BG: "#F6F5F1",
        EXP_FOOTER_LINKS: "#7A7A7E",
        EXP_PURPLE: "#5C20CF",
        EXP_MODAL_LABEL: "#707070",
        EXP_FIELD_READ: "#F2F2F2",
        EXP_PO_RED: "#F81F1F",
        EXP_PO_GREEN: "#57B250",
        EXP_PO_ORANGE: "#FBA320",
      },
      left: {
        EXP_LEFT_MODAL: "774.59px",
      },
      top: {
        EXP_MODAL_TOP: "375.04px",
      },
      height: {
        EXP_INP_HGT: "48px",
        EXP_HEADING: "36px",
        EXP_MODAL_HGT: "449px",
        EXP_FOOTER_HGT: "200px",
        EXP_MODAL_TP_HGT: "594px",
        EXP_CENTER_HGT: "368px",
        EXP_MSG_HGT: "60px",
        EXP_TEXTBOX_HGT: "120px",
        EXP_MIN_BOX_HGT: "215px",
        EXP_HBL_INP_HGT: "40px",
        EXP_SM_BTN_HGT: "21px",
        EXP_BIG_INP: "80px",
        EXP_JMBO_TB: "180px",
        EXP_TABLE_INP: "57px",
        EXP_DIALOG: "458px",
        EXP_SMALL_MODAL: "205px",
      },
      width: {
        EXP_WID: "520px",
        EXP_INP_WID: "320px",
        EXP_MODAL_WID: "520px",
        EXP_BTN_WID: "240px",
        EXP_TP_WID: "587px",
        EXP_TP_BTN_WID: "200px",
        EXP_CENTER_WID: "487px",
        EXP_MSG_WID: "490px",
        EXP_TABLE_WID: "1230px",
        EXP_HBL_INP_WID: "180px",
        EXP_TEXTBOX_WID: "320px",
        EXP_SM_BTN_WID: "135px",
        EXP_BIG_INP: "400px",
        EXP_JMBO_TB: "800px",
        EXP_TABLE_INP: "166px",
        EXP_PAGE: "860px",
        EXP_DIALOG: "447px",
        EXP_SMALL_MODAL: "273px",
      },
      borderRadius: {
        EXP_INP_BR: "4px",
        EXP_BTN_BR: "6px",
      },
      fontWeight: {
        EXP_WGT: "500",
        EXP_LABEL_WGT: "300",
        EXP_INP_WGT: "400",
        EXP_MODAL_HEAD: "600",
      },
      padding: {
        EXP_BTN_PDNG: "13.5px,24px",
      },
      border: {
        EXP_BORDER: "0.75px solid #BBBBBB",
      },
      fontSize: {
        EXP_HEADING_SIZE: "24px",
        EXP_HEADING_SIZE_2: "18px",
        EXP_TEXT: "12px",
        HBL_HEADING: "32px",
        EXP_BTN_TEXT: "14px",
        EXP_MODAL_TEXT: "22px",
        EXP_TT_TEXT: "16px",
        EXP_NAME_HEADING: "20px",
        EXP_SMALL_TEXT: "10px",
        EXP_TINY_TEXT: "8px",
      },
      letterSpacing: {
        EXP_HEADING: "0.5px",
      },
      fontFamily: {
        poppins: ["Poppins"],
      },
    },
  },
  plugins: [],
} satisfies Config;
